# Generated by Django 5.1.6 on 2025-03-04 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(max_length=50)),
                ('required_points', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='biomes/')),
                ('is_unlocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EcoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='eco_challenge.biome')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('proof_description', models.TextField(blank=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='task_proofs/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco_challenge.ecotask')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('total_points', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('completed_tasks', models.ManyToManyField(through='eco_challenge.TaskCompletion', to='eco_challenge.ecotask')),
                ('unlocked_biomes', models.ManyToManyField(to='eco_challenge.biome')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='user_progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco_challenge.userprogress'),
        ),
        migrations.AlterUniqueTogether(
            name='taskcompletion',
            unique_together={('user_progress', 'task')},
        ),
    ]
